---
- name: Configure XRDP on GCP Compute Engine (ubuntu VM)
  hosts: master
  become: yes
  vars:
    rdp_user: "{{ RDP_USER }}"
    rdp_pass: "{{ RDP_PASS }}"
    caido_version: "v0.33.0"
  roles:
    - role: apply
